### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by brunodpoliveira** [brunolcarli/Jion#6]
O seguinte erro ocorre quando se tenta executar qualquer comando "make" :

`django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.`

Mesmo com uma SECRET_KEY correta na configuração de todos os arquivos na pasta Jion/jion/environment 

Isso se resolve reescrevendo a seguinte linha em Jion/jion/settings/development.py:
`SECRET_KEY = os.environ.get('SECRET_KEY', '')`
Substituindo `os.environ.get('SECRET_KEY', '')` pela chave

O programa então executa os comandos "make" corretamente

Detalhes:
Sistema: Ubuntu 20.04 - Intel i3, GTX 1050, 3GB RAM
Seguindo as instruções de como rodar localmente (o problema não ocorre quando se cria uma imagem no docker)

**Comment by brunolcarli** [comment]
Como descrito no arquivo `README.md` 👍 

> Há um arquivo template para definição das variáveis de ambiente em: jion/environment/template, crie um novo arquivo contendo suas variáveis e exporte-as:

`source jion/environment/seu_arquivo`

O arquivo contém o conteúdo para que vc supostamente preencha com algum valor:

```
export SECRET_KEY=<your_secret_key>
```

Quanto ao 
> O programa então executa os comandos "make" corretamente

Você poderia ser mais específico dizendo **qual comando**  do makefile não funciona , como vc executou e qual erro retornado.

Recomendo você continuar a tirar esse tipo de dúvida no canal `#suporte` do servidor discord da LUCI antes de abrir a tarefa no Github.

Como esta tarefa não representa um bug real estou fechando a tarefa.

;)
